### ISSUE TITLE
Dart 2 incompatible

### ISSUE THREAD

**Issue by suragch** [adaojunior/pusher#18]
Are you still willing to maintain this project? I'm interested in using it and possibly helping work on the code. 

How much work would it require to migrate this to Dart 2?

**Comment by adaojunior** [comment]
Hi @suragch, yes, I'll migrate it to Dart2, I believe it won't take too much time since there's a tool to automatically upgrade Dart1 to Dart2.

**Comment by adaojunior** [comment]
@suragch this package is now compatible with Dart2, let me know if it works for you.

https://pub.dartlang.org/packages/pusher/versions/1.0.0-beta

**Comment by suragch** [comment]
Thanks for the quick response and update. I don't know how the pub pages get updated, but you can probably update it so that it doesn't say "Dart 2 incompatible" anymore. I'll let you know later how it works, but I am still working on learning server-side Dart right now so I'm not quite ready to test it.

**Comment by adaojunior** [comment]
It only shows "Dart 2 incompatible" on the version `0.3.0`, if you click on `1.0.0-beta` that message will disappear.
