### ISSUE TITLE
How to set cluster?

### ISSUE THREAD

**Issue by ThaDaVos** [adaojunior/pusher#20]
I'm trying to use this package in a Flutter test app but I'm getting an  'Unknow auth_key' response - after some googling I found out this is because of the `cluster` setting which seems unsupported in this library...

Any known way to fix this?

**Comment by adaojunior** [comment]
I'll add support the `cluster` setting soon, and I'll let you know when it is posted to pub.

**Comment by ThaDaVos** [comment]
When is the ETA of this support?

**Comment by adaojunior** [comment]
I believe I'll have it on pub in the next 2 days.

**Comment by adaojunior** [comment]
@dvdbot it is now available on https://pub.dartlang.org/packages/pusher/versions/1.0.1-beta

You just need to pass the cluster on `PusherOptions`.
