### ISSUE TITLE
Ability to subscribe to an event channel.

### ISSUE THREAD

**Issue by bimsina** [adaojunior/pusher#24]
How do I subscribe my client to an event channel and listen for when the channel is triggered?

**Comment by adaojunior** [comment]
HI @bimsina, it doesn't support listening to events on a channel. Which platform are you using (web, flutter, io)?

**Comment by bimsina** [comment]
Flutter

**Comment by adaojunior** [comment]
Yeah, sorry this package doesn't support Flutter right now, you can find other options at https://pub.dev/packages?q=pusher+flutter.

**Comment by bimsina** [comment]
I found another [package ](https://pub.dev/packages/pusher_websocket_flutter) that did the job. Anyway, thanks for the response. Appreciate it!
