### ISSUE TITLE
Is there support for chatkit?

### ISSUE THREAD

**Issue by kaciula** [adaojunior/pusher#26]
Hi.

I want to use ChatKit from pusher.com in a flutter app and I am not sure where to start from. From what I can see, this package has support only for channels. Is that right?

Can you point me in the right direction? Thank you.

**Comment by adaojunior** [comment]
Hi @kaciula 

Currently, this package only supports the Pusher HTTP API. 

I built this package a couple of years ago, and I'm not very familiar with Flutter. If you [search on pub.dev](https://pub.dev/packages?q=pusher) you will find Flutter related pusher packages, and I haven't tried any of them, so I cannot tell you which one the best.

I'm looking into refactoring this package, I may add flutter support, but I don't have a time estimate yet.

I'll keep you updated if anything changes concerning support to ChatKit.
