### ISSUE TITLE
handshake error when connecting to https, works fine with http

### ISSUE THREAD

**Issue by LtotheWT** [adaojunior/pusher#28]
HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: ok(handshake.cc:354))

is there any configuration that I need to do on client side ?

can we have a badCertificateCallback like in HttpClient ?

static HttpClient client = new HttpClient()
    ..badCertificateCallback = (_certificateCheck);

static bool _certificateCheck(X509Certificate cert, String host, int port) =>
      host == 'local.domain.ext';

**Comment by adaojunior** [comment]
Hi @LtotheWT, this library was built to be used on the server side. It does not work on Browsers or Flutter. You will find alternatives to it on https://pub.dev.

**Comment by LtotheWT** [comment]
i added badCertificateCallback and its working now, thanks for the repo mate
